/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import tinymce from "@sklinet/strapi-plugin-tinymce/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiChatgpt from "strapi-chatgpt/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import wysiwygReactMdEditor from "strapi-plugin-wysiwyg-react-md-editor/strapi-admin";
import wysiwyg from "../../src/plugins/wysiwyg/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    tinymce: tinymce,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-chatgpt": strapiChatgpt,
    "rest-cache": restCache,
    "wysiwyg-react-md-editor": wysiwygReactMdEditor,
    wysiwyg: wysiwyg,
  },
});
